# Generated by Django 4.0.4 on 2022-06-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('total_points', models.IntegerField()),
                ('weightage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('student_id', models.CharField(default=None, max_length=9)),
                ('group_title', models.CharField(max_length=250)),
                ('marks', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('eligible_student', models.ManyToManyField(blank=True, related_name='project', to='accounts.student')),
                ('enrolled_faculty', models.ManyToManyField(blank=True, related_name='enrolled_faculty', to='accounts.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='student_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_pid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('status', models.IntegerField(default=-1)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('sub_pdf_name', models.CharField(max_length=250)),
                ('assignment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='sub_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project_area', models.CharField(max_length=200)),
                ('sub_project_topic', models.CharField(max_length=200)),
                ('sub_project_pdf', models.FileField(blank=True, upload_to='sub_project/')),
                ('max_cap', models.IntegerField()),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('registred_student', models.ManyToManyField(blank=True, related_name='registred_project', to='accounts.student')),
                ('related_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.grp')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='p_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project_type'),
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('assigned_faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='grp',
            name='sub_project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_project'),
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.IntegerField()),
                ('assigned_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
    ]
