# Generated by Django 4.0.4 on 2022-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignment_grp_project_project_type_student_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grp',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='grp',
            name='marks',
        ),
        migrations.AlterField(
            model_name='grp',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
