# Generated by Django 4.0.4 on 2022-06-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_grp_group_id_remove_grp_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='grp_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.IntegerField()),
                ('sub_proj_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('sid', models.CharField(max_length=100)),
                ('marks', models.FloatField(default=0)),
            ],
        ),
    ]
