# Generated by Django 4.0.4 on 2022-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_grp_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='assigned_faculty',
        ),
        migrations.AddField(
            model_name='committee',
            name='assigned_faculty',
            field=models.ManyToManyField(related_name='in_committee', to='accounts.faculty'),
        ),
    ]
