# Generated by Django 4.0.4 on 2022-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_committee_assigned_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
