# Generated by Django 4.0.4 on 2022-06-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_schedule_date_alter_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='committee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.committee'),
        ),
    ]
