# Generated by Django 4.0.4 on 2022-07-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_schedule_committee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.assignment'),
        ),
    ]
