# Generated by Django 4.0.4 on 2022-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_submission_assignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_pdf_name',
            field=models.FileField(upload_to='submissions'),
        ),
    ]
