# Generated by Django 4.0.4 on 2022-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_submission_sub_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sub_pdf_name',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
