# Generated by Django 4.0.5 on 2022-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_submission_time_stamp_alter_submission_sub_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grp_map',
            name='final_marks',
            field=models.FloatField(default=0),
        ),
    ]
